/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.x21.ui.internal.X21Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class X21UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return X21Activator.getInstance().getInjector("dk.sdu.mmmi.mdsd.X21");
	}

}
