/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.DataDecl#getDeclNames <em>Decl Names</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.DataDecl#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getDataDecl()
 * @model
 * @generated
 */
public interface DataDecl extends Declaration
{
  /**
   * Returns the value of the '<em><b>Decl Names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl Names</em>' attribute list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getDataDecl_DeclNames()
   * @model unique="false"
   * @generated
   */
  EList<String> getDeclNames();

  /**
   * Returns the value of the '<em><b>Types</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' attribute list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getDataDecl_Types()
   * @model unique="false"
   * @generated
   */
  EList<String> getTypes();

} // DataDecl
