/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Element#getNodeName <em>Node Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Element#getFunction <em>Function</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Element#getLambda <em>Lambda</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Element#getOutputName <em>Output Name</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Name</em>' attribute.
   * @see #setNodeName(String)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getElement_NodeName()
   * @model
   * @generated
   */
  String getNodeName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.Element#getNodeName <em>Node Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Name</em>' attribute.
   * @see #getNodeName()
   * @generated
   */
  void setNodeName(String value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getElement_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.Element#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

  /**
   * Returns the value of the '<em><b>Lambda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' containment reference.
   * @see #setLambda(Lambda)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getElement_Lambda()
   * @model containment="true"
   * @generated
   */
  Lambda getLambda();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.Element#getLambda <em>Lambda</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' containment reference.
   * @see #getLambda()
   * @generated
   */
  void setLambda(Lambda value);

  /**
   * Returns the value of the '<em><b>Output Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Name</em>' attribute.
   * @see #setOutputName(String)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getElement_OutputName()
   * @model
   * @generated
   */
  String getOutputName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.Element#getOutputName <em>Output Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Name</em>' attribute.
   * @see #getOutputName()
   * @generated
   */
  void setOutputName(String value);

} // Element
