/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Exp
{
} // Expression
