/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Function#getLambda <em>Lambda</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getFunction()
 * @model
 * @generated
 */
public interface Function extends Declaration
{
  /**
   * Returns the value of the '<em><b>Lambda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' containment reference.
   * @see #setLambda(Lambda)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getFunction_Lambda()
   * @model containment="true"
   * @generated
   */
  Lambda getLambda();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.Function#getLambda <em>Lambda</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' containment reference.
   * @see #getLambda()
   * @generated
   */
  void setLambda(Lambda value);

} // Function
