/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.IfStatement#getStatement <em>Statement</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.IfStatement#getTrueExpression <em>True Expression</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.IfStatement#getFalseExpression <em>False Expression</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends Atomic
{
  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference.
   * @see #setStatement(LogicExp)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getIfStatement_Statement()
   * @model containment="true"
   * @generated
   */
  LogicExp getStatement();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.IfStatement#getStatement <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' containment reference.
   * @see #getStatement()
   * @generated
   */
  void setStatement(LogicExp value);

  /**
   * Returns the value of the '<em><b>True Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>True Expression</em>' containment reference.
   * @see #setTrueExpression(Exp)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getIfStatement_TrueExpression()
   * @model containment="true"
   * @generated
   */
  Exp getTrueExpression();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.IfStatement#getTrueExpression <em>True Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>True Expression</em>' containment reference.
   * @see #getTrueExpression()
   * @generated
   */
  void setTrueExpression(Exp value);

  /**
   * Returns the value of the '<em><b>False Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>False Expression</em>' containment reference.
   * @see #setFalseExpression(Exp)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getIfStatement_FalseExpression()
   * @model containment="true"
   * @generated
   */
  Exp getFalseExpression();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.IfStatement#getFalseExpression <em>False Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>False Expression</em>' containment reference.
   * @see #getFalseExpression()
   * @generated
   */
  void setFalseExpression(Exp value);

} // IfStatement
