/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.LetBinding#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.LetBinding#getBinding <em>Binding</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.LetBinding#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getLetBinding()
 * @model
 * @generated
 */
public interface LetBinding extends Atomic
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getLetBinding_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.LetBinding#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding</em>' containment reference.
   * @see #setBinding(Exp)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getLetBinding_Binding()
   * @model containment="true"
   * @generated
   */
  Exp getBinding();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.LetBinding#getBinding <em>Binding</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding</em>' containment reference.
   * @see #getBinding()
   * @generated
   */
  void setBinding(Exp value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Exp)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getLetBinding_Body()
   * @model containment="true"
   * @generated
   */
  Exp getBody();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.LetBinding#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Exp value);

} // LetBinding
