/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.NewStatement#getCustomName <em>Custom Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.NewStatement#getParamNames <em>Param Names</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.NewStatement#getParamValues <em>Param Values</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getNewStatement()
 * @model
 * @generated
 */
public interface NewStatement extends Atomic
{
  /**
   * Returns the value of the '<em><b>Custom Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Name</em>' attribute.
   * @see #setCustomName(String)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getNewStatement_CustomName()
   * @model
   * @generated
   */
  String getCustomName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.NewStatement#getCustomName <em>Custom Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Name</em>' attribute.
   * @see #getCustomName()
   * @generated
   */
  void setCustomName(String value);

  /**
   * Returns the value of the '<em><b>Param Names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Names</em>' attribute list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getNewStatement_ParamNames()
   * @model unique="false"
   * @generated
   */
  EList<String> getParamNames();

  /**
   * Returns the value of the '<em><b>Param Values</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.x21.Exp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Values</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getNewStatement_ParamValues()
   * @model containment="true"
   * @generated
   */
  EList<Exp> getParamValues();

} // NewStatement
