/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>None</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getNone()
 * @model
 * @generated
 */
public interface None extends Atomic
{
} // None
