/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.x21;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stream</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Stream#getInputs <em>Inputs</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Stream#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getStream()
 * @model
 * @generated
 */
public interface Stream extends Declaration
{
  /**
   * Returns the value of the '<em><b>Inputs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inputs</em>' attribute list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getStream_Inputs()
   * @model unique="false"
   * @generated
   */
  EList<String> getInputs();

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.x21.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getStream_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Stream
